export const middleSlider1 = 'https://i.ibb.co/nrzNZSY/middle-Slider1.jpg'
export const middleSlider2 =
  'https://vasabisushi.ru/wp-content/uploads/2019/04/naslajdenie.jpg'
export const middleSlider3 =
  'https://vasabisushi.ru/wp-content/uploads/2019/04/banderos.jpg'
export const middleSlider4 = 'https://i.ibb.co/t3mGVT4/middle-Slider4.jpg'
export const middleSlider5 = 'https://i.ibb.co/KLrS1hc/middle-Slider5.jpg'
export const middleSlider6 = 'https://i.ibb.co/n7QYKp0/middle-Slider6.jpg'
export const middleSlider7 = 'https://i.ibb.co/Kx0tSCn/middle-Slider7.jpg'
export const middleSlider8 = 'https://i.ibb.co/Y7nMXF6/middle-Slider8.jpg'
export const middleMenu1 = 'https://i.ibb.co/TcN7J5k/middle-Menu1.png'
export const middleMenu2 = 'https://i.ibb.co/bmC9x25/middle-Menu2.png'
export const middleMenu3 = 'https://i.ibb.co/GpBt99N/middle-Menu3.png'
export const middleMenu4 = 'https://i.ibb.co/TYPF468/middle-Menu4.png'
export const middleMenu5 = 'https://i.ibb.co/qJwMcYP/middle-Menu5.png'
export const slider1 = 'https://i.ibb.co/9NFG8RZ/slider-Menu1.jpg'
export const slider2 = 'https://i.ibb.co/CWjwZj2/slider-Menu2.jpg'
export const slider3 = 'https://i.ibb.co/C0fsSqR/slider-Menu3.jpg'
export const slider4 = 'https://i.ibb.co/zZh8vcX/slider-Menu4.jpg'
export const slider5 = 'https://i.ibb.co/6Dphfvd/slider-Menu5.webp'
