export { OrdersHistory } from './OrdersHistory/OrdersHistory'
export { PersonalInfo } from './PersonalInfo/PersonalInfo'
export { Favourites } from './Favourites/Favourites'
export { Subscribe } from './Subscribe/Subscribe'
export { Delivery } from './Delivery/Delivery'
export { Logout } from './Logout/Logout'
